### ISSUE TITLE
Is this plugin vulnerable due to use of the onelogin library?

### ISSUE THREAD

**Issue by TrentLewisAU** [cosmocode/dokuwiki-plugin-adfs#10]
I apologise if I am way off track with this. I'm by no means a PHP developer. I'm coming from a sysadmin perspective looking to implement SAML with dokuwiki in production.

This plugin works perfectly for my needs, however I noticed that this plugin seems to rely on a onelogin library and there seem to have been some vulnerabilities in that library reported since the last update to this plugin.
https://github.com/onelogin/php-saml#warning
Can anybody help me to understand why this plugin is or isn't vulnerable to know vulnerabilities?
Cheers,

**Comment by splitbrain** [comment]
It might be vulnerable. Unfortunately I don't have access to an ADFS setup currently so I can not look into this myself. Any help welcome!

**Comment by TrentLewisAU** [comment]
@splitbrain thanks so much for the response, and thanks for your work on Dokuwiki!

Is it correct to say that this plugin was built using and older version of this library? Or am I jumping to incorrect conclusions by assuming that this folder is related? https://github.com/cosmocode/dokuwiki-plugin-adfs/tree/master/phpsaml/onelogin? 

I'm guessing that perhaps this is the relevant folder? https://github.com/onelogin/php-saml/tree/master/lib/Saml

**Comment by splitbrain** [comment]
Yes, it's an older version of that library. Simply exchanging the library will most likely not work because it changed significantly.

PS: CosmoCode is available for hire if that's an option for you

**Comment by splitbrain** [comment]
library has been updated a while ago.
