### ISSUE TITLE
Upgrade of ADFS Plugin in Docuwiki breaks ADFS

### ISSUE THREAD

**Issue by jamesber50** [cosmocode/dokuwiki-plugin-adfs#11]
Upgrading the plugin to the 2018-05-30 version seems to break our ADFS installation with the below error. Reverting the snapshot makes the site accessible again.

 ADFS: Invalid issuer in the Assertion/Response (expected 'set me', got 'http://sample.domain.com/adfs/services/trust')

**Comment by splitbrain** [comment]
did you set the idPEntityID config option?

**Comment by jamesber50** [comment]
Got it. It seems there is a newly added field which did not auto-ingest post plugin upgrade (as well as the ADFS Helper page) and it broke as a result. It also seems some of the variables changed which was also throwing off the SAML authentication after applying the new plugin. It is working now however!

Now to hopefully fix the rest of our dokuwiki issues. 😊

Thanks so much for your prompt response!

James Bertram

IT Administrator – AvePoint, Inc.

P: +1 201-793-1111 X1339| james.bertram@avepoint.com<mailto:james.bertram@avepoint.com> | www.AvePoint.com<http://www.avepoint.com/>

Follow us on Facebook<http://www.facebook.com/avepointinc>, Twitter<http://twitter.com/AvePoint_Inc>, and LinkedIn<http://www.linkedin.com/company/avepoint/>!
