### ISSUE TITLE
Setup with SimpleSAMLphp?

### ISSUE THREAD

**Issue by poVoq** [cosmocode/dokuwiki-plugin-adfs#9]
On the dokuwiki page it says that this plugin is tested with simpleSAMLphp. I have set up a SimpleSAMLphp IDP server and used the https://idpserverurl/saml/saml2/idp/SSOService.php in the settings of this plugin.
I also changed the attribute names and supplied it with the certificate.

However when I click on the login button now it redirects me to the IDP page but with the error message:

> Metadata not found
> Unable to locate metadata for 'https://urlofmydokuwiki'

specificly:

> SimpleSAML_Error_MetadataNotFound: METADATANOTFOUND('%ENTITYID%' => '\'https://urlofmydokuwiki'')

Any ideas?

Also how can I access the settings of my dokuwiki easily again now as obviously I can't log in regularly.

Thanks!

**Comment by splitbrain** [comment]
I did not add that sentence to the page. I never worked with simplesamlephp and this plugin, but apparently some user got it working. I can't help you there. maybe ask in the forum.

**Comment by dugite-code** [comment]
I know this is an old closed issue but I've just gotten this working so I thought I would post an update on this issue if anyone else is looking for the solution.

1. Follow a tutorial to setup SimpleSAMLPHP with ssl eg: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-simplesamlphp-for-saml-authentication-on-ubuntu-18-04

2. Navigate to the adfs Federation metadata address: `https://yourwiki/doku.php?do=adfs` and download the xml file

3. Navigate to the SimpleSAMLphp metadata converter `https://example.tld/simplesaml/admin/metadata-converter.php` and paste the xml contents there.

![image](https://user-images.githubusercontent.com/12742064/101567116-326d3080-3a0b-11eb-9b68-62443e2dc562.png)

4. Add this output to the SimpleSAMLphp saml20-sp-remote.php file eg: `/var/www/simplesamlphp/metadata/saml20-sp-remote.php`  **Edit:** delete the 'expire' line as unless you are reguarly updating the meta data will lock you out.

5. In Dokuwiki ADFS settings set the idPEntityID to your simpleSAMLphp metadata url eg: `https://example.tld/simplesaml/saml2/idp/metadata.php`

6. In Dokuwiki ADFS settings set the endpoint to your simpleSAMLphp URL target eg: `https://example.tld/simplesaml/saml2/idp/SSOService.php`

### Additional Notes
* Make sure you map your user attributes correctly or it will error out.
* If you get locked out delete the line `$conf['authtype'] = 'adfs';` from `conf/local.php` to switch back to authplain
* I am using the linuxserver dokuwiki docker container and had to add php7-dom to the docker file.
